dev-deploy:
  stage: deploy
  only:
    - master
  script:
    - npm run babel
    - git add dist/*
    - git commit -m "deploy"
    - git push origin master

pages:
  cache:
    paths:
      - node_modules
  script:
    - npm install 
    - npm run styleguide:build
    - mv styleguide public 
  artifacts:
    paths:
      - public
  only:
    - release


